### PR TITLE
[MIG] password_security: Migration to 15.0

### PR DESCRIPTION
**Pull request by rjpathan**

### CODE REVIEW

**Comment by PieterPaulussen** [comment]
@rjpathan One of the tests is failing. Care to update the PR with the appropriate fix?

**Review by PieterPaulussen — APPROVED** [review]
There's an unrelated test failing in `odoo.addons.auth_saml.tests.test_pysaml`
LGTM

**Comment by schout-it** [comment]
https://github.com/OCA/server-auth/pull/356/files#diff-2c1c11f2ce9b2571602f9b0185b57a72e738dd34a5381a6478d1f27a2264ee87R51
redirect_with_hash does not exist anymore, is now request.redirect from what I see

**Comment by rjpathan** [comment]
@schout-it redirect_with_hash has been replaced with redirect

**Comment by pfranck** [comment]
Can I help to improve something ?

**Comment by jans23** [comment]
Improvements in #456.

**Pull request closed without merging**
