### PR TITLE
[16.0][MIG] auth_oauth_autologin: Migration to 16.0

### PR DESCRIPTION
**Pull request by ARuz-Trey**
Standard migration from 13.0 to 16.0.

### CODE REVIEW

**Review by antonio-trey — APPROVED** [review]
👍🏻

**Review by miguel-poyatos — APPROVED** [review]

**Review by sbidoul — CHANGES_REQUESTED** [review]
Thanks for working on this. Can you please preserve the commit history by following the procedure: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Comment by sbidoul** [comment]
Can you also pick the improvements from https://github.com/OCA/server-auth/pull/511 ?

**Comment by andres-pcg** [comment]
> Can you also pick the improvements from #511 ?

Hey @ARuz-Trey thanks for your constribution. have you been able to check on this comment?

**Pull request closed without merging**
