### PR TITLE
[11.0][IMP] auth_saml

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**

### CODE REVIEW

**Comment by vincent-hatakeyama** [comment]
My company has signed the OCA CLA, I don’t understand why I get the message from the bot.

**Comment by pedrobaeza** [comment]
When did you send it? Maybe it's not still processed (it's a manual one). I prefer to squash some commits for not adding too much meaningless history for one module, but do it on your taste.

**Comment by vincent-hatakeyama** [comment]
XCG sent it two or three years ago.
Maybe it’s because my github username changed.

**Comment by pedrobaeza** [comment]
Yes, the problem then is the change of username, as the control is done through it. Please tell me the old username for switching it in the DB.

**Comment by vincent-hatakeyama** [comment]
Thank you for looking into this.
My old nickname was vincent-lhote.

**Review by lgharib — APPROVED** [review]

**Review by eilst — APPROVED** [review]
LGTM. I tested your PR locally. It works well. :+1:

**Comment by max3903** [comment]
@vincent-hatakeyama Can you fix the Travis error please?

**Comment by vincent-hatakeyama** [comment]
I fixed the error linked with the auth_saml module (there are pylint errors on other modules).

**Comment by moylop260** [comment]
@eilst 

FYI I'm fixing pylint-odoo internal error:
 - https://github.com/OCA/pylint-odoo/pull/261

But the output after fixing will be:
```bash
auth_saml/NEWS.rst:1: [E7901(rst-syntax-error), ]  Anonymous hyperlink mismatch: 0 references but 1 targets.|See "backrefs" attribute for IDs.
auth_saml/scripts/clear_passwords.sql:1: [W7930(file-not-used), ]  not used from manifest
auth_saml/scripts/2.0-cleanup.sql:1: [W7930(file-not-used), ]  not used from manifest
************* Module auth_saml.controllers.main
auth_saml/controllers/main.py:213: [E8102(invalid-commit), AuthSAMLController.signin] Use of cr.commit() directly - More info https://github.com/OCA/odoo-community.org/blob/master/webs$
te/Contribution/CONTRIBUTING.rst#never-commit-the-transaction
```

Could you check it, if it is possible fixing it?

**Comment by moylop260** [comment]
@pedrobaeza @max3903 
Could you enable the CLA of @vincent-hatakeyama (AKA @vincent-lhote), please?

**Comment by vincent-hatakeyama** [comment]
The targets in the NEWS.rst can be used to point at specific version/chapter from another documentation using intersphinx. I think that specific error should be ignored.

**Comment by moylop260** [comment]
Hi @vincent-hatakeyama 

Is possible using [backrefs](http://docutils.sourceforge.net/docs/ref/doctree.html#backrefs) instead?

Or another way without errors from: http://rst.aaroniles.net :
 - Screen Shot 2019-10-01 at 12 33 33 PM

**Comment by moylop260** [comment]
@vincent-hatakeyama 
I will merge it since that it is approved and the CI is green.
We can work about false red about RST from another issue/PR

/ocabot merge

**Comment by moylop260** [comment]
@vincent-hatakeyama 
Could you squash all commits into one, please?

**Comment by vincent-hatakeyama** [comment]
After trying to rebase the commits to squash them and having too many conflicts, I just created a new branch where I squashed the commits while doing a merge.

I had previously fixed the conflicts with the new 11.0 head.

**Comment by dreispt** [comment]
@vincent-hatakeyama I fixed your CLA records.
The build is red so we won't be able to merge. Con you fix that please?

**Comment by dreispt** [comment]
@vincent-hatakeyama Thank you for getting back to this after so long.

**Comment by vincent-hatakeyama** [comment]
I’ve fixed a couple of flake8 errors.

I’ve tried to run what is done in travis locally but that just does not work.

There’s other things I don’t know how to fix:
- auth_saml needs the lasso library installed and the python bindings. That what this error is about: https://travis-ci.org/github/OCA/server-auth/jobs/668795602#L754
- the linter complains about a couple things, but those where not changed by the PR. The commit was already present (and I believe that any module implementing an auth has to do one), and the SQL file were already present. I could delete them if needed and probably include them in the documentation instead, or maybe include them from the documentation.

**Comment by pedrobaeza** [comment]
@Yajo FYI

**Comment by yajo** [comment]
And **not** this lasso: https://pypi.org/project/lasso/
**This** lasso: https://lasso.entrouvert.org/

**Comment by vincent-hatakeyama** [comment]
The python3-lasso is available in debian stable for a while: https://packages.debian.org/buster/python3-lasso.

What is stopping this from being merged?

**Comment by moylop260** [comment]
@randallvx 

Could you give feedback, please?

**Comment by vincent-hatakeyama** [comment]
I’ve been waiting for feedback but did not receive any.

Still wondering why this has not been merged.

**Pull request closed without merging**
