### PR TITLE
[12.0][MIG] auth_admin_passkey

### PR DESCRIPTION
**Pull request by fkantelberg**
Hi,

this is the migration of the auth_admin_passkey from v10.

Because of the concerns regarding to the GDPR from the mailing list I'll try to suggest some further improvements in a following PR.

### CODE REVIEW

**Comment by mohamedhagag** [comment]
just tested it , working fine .

**Comment by alexis-via** [comment]
When using this PR, we get this warning in the logs of Odoo:

```
2019-07-23 12:03:44,077 31490 WARNING test1 odoo.addons.base.models.res_config: Methods that start with `get_default_` are deprecated. Override `get_values` instead(Method get_default_auth_admin_passkey_send_to_admin) 
2019-07-23 12:03:44,077 31490 WARNING test1 odoo.addons.base.models.res_config: Methods that start with `get_default_` are deprecated. Override `get_values` instead(Method get_default_auth_admin_passkey_send_to_user)
```

**Comment by fkantelberg** [comment]
@alexis-via Should be removed now.

**Comment by mohamedhagag** [comment]
Should we merge ?

**Comment by fkantelberg** [comment]
As promised the suggested improvement regarding the GDPR in #129.

**Pull request closed without merging**
