### PR TITLE
[12.0][IMP]auth_admin_passkey: Block loggin using admin passkey with some users.

### PR DESCRIPTION
**Pull request by manuelregidor**
New option to block the ability of logging into selected users accounts using the admin passkey.

### CODE REVIEW

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Comment by HaraldPanten** [comment]
@gurneyalex @pedrobaeza any clue about why might be runbot failing?

THX!

**Comment by pedrobaeza** [comment]
It's brown, which means a warning, but such warning is not accessible. Maybe Python 3.5 deprecation or a field with same label.

**Comment by HaraldPanten** [comment]
> It's brown, which means a warning, but such warning is not accessible. Maybe Python 3.5 deprecation or a field with same label.

THX Pedro

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
