### PR TITLE
[16.0][ADD] auth_jwt_server_env

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Comment by sbejaoui** [comment]
@sbidoul , can you please check why the test is failing

**Comment by sbidoul** [comment]
That was because the presence of the server env config module without configuration overrides demo data with null values.
I put the new module in a separate test group.

**Review by sbidoul — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]
Functional test and code review.

**Review by qgroulard — APPROVED** [review]

**Pull request merged**
