### PR TITLE
[11.0][IMP] Show the secret code in the authenticator

### PR DESCRIPTION
**Pull request by fkantelberg**
Hello,

this is the same as [#1409](https://github.com/OCA/server-tools/pull/1409) but for 11.0 and should allow the usage of more devices with this auth_totp.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by fkantelberg** [comment]
@pedrobaeza Thanks for the quick approval. I pulled the fix of auth_brute_force into the branch and the CI is working again. Do I need another approval?

**Comment by pedrobaeza** [comment]
You should rebase instead of pulling, and yes, we need a second approval.

**Review by kmatthes — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I hope @kmatthes to contribute soon with more things than the approval :wink:

**Comment by kmatthes** [comment]
I guess I deserve that, @pedrobaeza . I always have a bad presence on stage. But believe me, behind the scenes I make sure that the play is a success. :)

**Comment by pedrobaeza** [comment]
Don't be shy to appear on the front stage, hehe. We are here for helping you kick-in :smiley:

**Pull request merged**
