### PR TITLE
[11.0] keychain: improve ACL and allow storing ssh keys as password

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
see also https://github.com/OCA/server-tools/pull/1295

**Comment by Cedric-Pigeon** [comment]
@lmignon

**Review by lmignon — APPROVED** [review]
LGTM (code only)

**Review by hparfr — APPROVED** [review]

**Review by hparfr — CHANGES_REQUESTED** [review]
You have to change clear_password type and increment version number.

**Comment by Cedric-Pigeon** [comment]
@hparfr OK, done. Thanks

**Review by hparfr — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
