### PR TITLE
[10.0][FIX] remove static folder introduce preloadable key in auth_api_key

### PR DESCRIPTION
**Pull request by ntsirintanis**
[related](https://github.com/OCA/server-auth/pull/84) @hbrunn

### CODE REVIEW

**Comment by hbrunn** [comment]
in this case it's the module pulling server_environment, and this raises when not configured

**Review by hbrunn — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by sbidoul** [comment]
Note the bot regenerated `static/description/index.html`. I see `preloadable=False` influences the icon generator but not the readme generator.

**Comment by hbrunn** [comment]
thanks for the heads up, I created https://github.com/OCA/maintainer-tools/issues/426 for this

**Pull request closed without merging**
