### PR TITLE
[FIX] password_security: Error 500 when login with bad password

### PR DESCRIPTION
**Pull request by yajo**
Without this patch, when logging in, and website addon was installed, and you failed the password, you get error 500.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is red and please change version number

**Comment by yajo** [comment]
It should be :green_heart: now.

**Review by hieulucky111 — APPROVED** [review]

**Comment by chienandalu** [comment]
This repo's runbots are failing:

image

**Comment by yajo** [comment]
@chienandalu Remove the `s` from `https`. Not sure why it's happening, but that makes it work here.

**Comment by chienandalu** [comment]
@Yajo Yeah, I tried that before, but it redirects to the https one...

**Comment by yajo** [comment]
Try in a private window, before visiting the https version (possibly it sets a HSTS header)

**Comment by chienandalu** [comment]
No luck. Does it work for you?: http://runbot.odoo-community.org:8796/?db=3329552-27-bf3417-all

**Comment by yajo** [comment]
Yes... :confused: 

If you try on Firefox? Private window.

**Comment by chienandalu** [comment]
Ok, I had to try it in https://www.browserling.com. It works as expected :smile:

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by yajo** [comment]
> Ok, I had to try it in https://www.browserling.com. It works as expected smile

TIL :astonished:

**Pull request merged**
