### PR TITLE
[MIG] auth_signup_verify_email: Migration to 16.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**
In the migration commit I'm changing:
- The way we import patch (now from unittest.mock)
- Remove the lang of the user because if it is not installed on the database Odoo returns an error

### CODE REVIEW

**Review by zaoral — APPROVED** [review]
@Bruno-Zanotti 
Hi Brunito
Thank you for the PR 

Look good +1
Best Regards

**Review by nguyenhk99 — APPROVED** [review]
LGTM!

**Comment by zuher83** [comment]
@sbidoul Is there a problem with migration? 🙄

**Review by tarteo — APPROVED** [review]
Thanks! Tested locally works perfectly

**Comment by anas2001abdullah** [comment]
Hi I downloaded this app and I am getting this error when sign up 
"secret must be unicode or bytes, not bool" from the odoo web signup controller
How to solve that please?

**Pull request merged**
