### PR TITLE
[FIX] password_security: translatable error message

### PR DESCRIPTION
**Pull request by yajo**
Without this patch, users must know English to understand why they cannot change their passwords.

@Tecnativa TT21381

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Are you sure in the context where the message is thrown, the language is known? (is it in the context to be evaluated or whatever?)

**Comment by yajo** [comment]
There's no reason why not. As long as this is inside a method, it should have a proper `self.env.lang`.

**Comment by pedrobaeza** [comment]
But as this can be done when setting first time the password not yet logged, I'm not sure about that.

**Comment by yajo** [comment]
Captura de pantalla de 2020-02-17 12-37-42

:point_up: It works, definitely.

**Comment by pedrobaeza** [comment]
OK, great

/ocabot merge minor

**Pull request merged**
