### PR TITLE
[17.0] [MIG] user_log_view

### PR DESCRIPTION
**Pull request by Tisho99**

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

**Comment by HaraldPanten** [comment]
@pedrobaeza This easy one might be useful for you. Could you have a quick look and merge, please?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration user_log_view
/ocabot merge nobump

**Pull request merged**
