### PR TITLE
[IMP][15.0]auth_saml: add tests and fix password reset when deactivating the config settings

### PR DESCRIPTION
**Pull request by leemannd**
Forward port of https://github.com/OCA/server-auth/pull/599

### CODE REVIEW

**Comment by gurneyalex** [comment]
@leemannd the CI is red;-)

**Comment by leemannd** [comment]
@gurneyalex It would be better now. It's a forward port of https://github.com/OCA/server-auth/pull/599
Do you want me to squash the commits together ?

**Review by gurneyalex — APPROVED** [review]

**Comment by vincent-hatakeyama** [comment]
> […] Do you want me to squash the commits together ?

Please squash and make sure that the commit message follows the usual OCA conventions.

**Comment by leemannd** [comment]
Hello @vincent-hatakeyama If it is ok for you a merge is welcome

**Pull request merged**
