### PR TITLE
[12.0][mig] auth_totp

### PR DESCRIPTION
**Pull request by fkantelberg**
Hi,

I migrated and tested it with different users. Seems to be stable so far despite the changes in odoo 12.

### CODE REVIEW

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Review by yweng8111 — APPROVED** [review]
Nice Job

**Comment by cornucopiaa** [comment]
@lmignon @pedrobaeza can you guys merge this one please, really looking forward to having TOTP in Odoo 12

**Comment by cornucopiaa** [comment]
thank you @pedrobaeza !

**Comment by fkantelberg** [comment]
thank you @nobd @pedrobaeza

**Pull request closed without merging**
