### PR TITLE
[17.0][MIG] auth_user_case_insensitive: Migration to 17.0

### PR DESCRIPTION
**Pull request by beagle-cloud**

### CODE REVIEW

**Review by MohamedOsman7 — APPROVED** [review]
LGTM

**Review by CRogos — APPROVED** [review]
Code + Test LGTM.

Commit history is not cleaned up: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

image

**Comment by CRogos** [comment]
@beagle-cloud are you still working on this PR?

**Comment by CRogos** [comment]
@pedrobaeza can you close this... superseded by https://github.com/OCA/server-auth/pull/641

**Pull request closed without merging**
