### PR TITLE
[15.0][MIG] auth_saml: Migrate to version 15.0

### PR DESCRIPTION
**Pull request by Camille0907**
Standard migration

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
LG 👍🏻

**Comment by damdam-s** [comment]
@OCA/community-maintainers can we go forward on this one please?
thank you very much

**Review by StephaneMangin — APPROVED** [review]

**Comment by vincent-hatakeyama** [comment]
Just tested this and it does not work correctly. It’s missing the commit put back with https://github.com/OCA/server-auth/commit/868df2830ceb4895ae6f857f4e6c957ba7905da3 that was removed in https://github.com/OCA/server-auth/commit/d29681920b9e8862044b4154ca4a8dca42078e39#diff-d051ee3f0ce073219b1c7ebc99bfa35206c9ebeefbf62df714fb8c800ad0310cL183.

**Pull request merged**
