### PR TITLE
[15.0][MIG] auth_api_key_server_env: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@simahawk can you pls take a look here?

**Review by simahawk — APPROVED** [review]

**Review by SilvioC2C — APPROVED** [review]

**Comment by simahawk** [comment]
@yankinmax if you are still on this topic, the next one would be https://github.com/OCA/server-auth/tree/14.0/auth_api_key_group

/ocabot merge nobump

**Comment by yankinmax** [comment]
@simahawk how could you solve this problem here: https://github.com/OCA/server-auth/pull/308? Should I try maybe the same?

**Comment by simahawk** [comment]
I restarted it and it passed

**Pull request merged**
