### PR TITLE
[12.0][mig] auth_totp_password_security

### PR DESCRIPTION
**Pull request by fkantelberg**
#88 recommended for testing because of issues with password_security.

Depends:
- [x] #114

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@fkantelberg please, rebase to resolve conflicts.

**Comment by fkantelberg** [comment]
@mreficent rebased as you wished

**Review by MiquelRForgeFlow — APPROVED** [review]
mark the box in your first comment

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
