### PR TITLE
[MIG] auth_brute_force: Migrate to v11

### PR DESCRIPTION
**Pull request by yajo**
- Remove Python coding headers.
- Remove v10 migration scripts.
- Standard py2-py3 changes.
- Do not encode POST data in tests, Odoo now uses `requests` for `HttpCase` connections.
- Include https://github.com/OCA/server-tools/pull/1219, https://github.com/OCA/server-tools/pull/1250 and https://github.com/OCA/server-tools/pull/1251

@Tecnativa

### CODE REVIEW

**Comment by yajo** [comment]
Not sure what's Github doing with this commit order:

captura de pantalla de 2018-05-22 12-32-01

But as you can see [here](https://github.com/Tecnativa/server-auth/commits/11.0-auth_brute_force/auth_brute_force), it's correctly done:

captura de pantalla de 2018-05-22 12-32-31

This should be ready to merge.

**Comment by pedrobaeza** [comment]
I think it's because it's ordered by date, not by commit insertion. I have seen this before in other cases.

**Review by pedrobaeza — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
but you can edit the commit date of the migration commit and change it to a posterior date 😎

**Comment by yajo** [comment]
It's not my job to fix Github :yum:

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
