### PR TITLE
remove group no one from saml provider

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why removing it?

**Comment by vincent-hatakeyama** [comment]
When you configure odoo to add SAML authentification, you shouldn’t need to activate debug/technical mode to access a very important menu.
For comparison, to access ldap settings with auth_ldap, you don’t need to activate debug.

**Comment by pedrobaeza** [comment]
OK, I let original authors to decide about this PR.

**Comment by alexey-pelykh** [comment]
Should this module & PR be considered abandoned due to a fact that module and PR has not been revisited for 5 months?

**Comment by pedrobaeza** [comment]
Yes, it can be considered that way.

**Comment by alexey-pelykh** [comment]
What would be your advice on this module? Since we do need it, yet waiting for original author to get back the module is not an option and some of changes from this PR seem valid

**Comment by vincent-hatakeyama** [comment]
I think this should be closed in favor of  #107 .

**Pull request closed without merging**
