### PR TITLE
[17.0][MIG] auth_oidc

### PR DESCRIPTION
**Pull request by ap-wtioit**
Migration of auth_oidc to 17.0

Info @wt-io-it

### CODE REVIEW

**Review by wtaferner — APPROVED** [review]

**Comment by wtaferner** [comment]
@sbidoul 
There we go, hope you will find time today to merge this 🙏🏼

**Review by sbidoul — APPROVED** [review]

**Comment by sbidoul** [comment]
Examined with my now favorite review command: `pip-wheel-diff "odoo-addon-auth_oidc==16.0.*" "git+https://github.com/oca/server-auth@refs/pull/620/head#subdirectory=auth_oidc`

**Pull request merged**
