### PR TITLE
[13.0][MIG] auth_ldaps

### PR DESCRIPTION
**Pull request by bodedra**

### CODE REVIEW

**Comment by bodedra** [comment]
@etobella @alexey-pelykh are you guys available to help?

**Comment by alexey-pelykh** [comment]
https://github.com/odoo/odoo/blob/13.0/addons/auth_ldap/__manifest__.py#L14 seems `ldap` is correct one and probably if auth_ldap is installed ,then no need to redeclare dependency

**Comment by alexey-pelykh** [comment]
Also, see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch about 2 separate commits with codestyle

**Comment by bodedra** [comment]
You mean `pre-commit run -a`?

Is it necessary of codestyle?

**Comment by bodedra** [comment]
Ah. I see. It failed.

**Comment by alexey-pelykh** [comment]
Almost there: first do the precommit as per link above, then migration

**Comment by bodedra** [comment]
Replaced by https://github.com/OCA/server-auth/pull/179

**Pull request closed without merging**
