### PR TITLE
[IMP] password_security: Set password update date for already existin…

### PR DESCRIPTION
**Pull request by keylor2906**
…g users that don't have it. This fixes the password expiration date and other validations that require an existing value for password update date.

[IMP] password_security: Simplify validation on password reset.

### CODE REVIEW

**Comment by maneandrea** [comment]
@moylop260 , @rolandojduartem could you review when CI passes?

@keylor2906 Could you check the CI? I think there are some reformatting issues

**Review by moylop260 — APPROVED** [review]
👍

**Review by maneandrea — APPROVED** [review]

**Comment by maneandrea** [comment]
@moylop260 When you have time could you merge this?

**Pull request merged**
