### PR TITLE
[17.0][MIG] auth_admin_passkey

### PR DESCRIPTION
**Pull request by amkarthik**
cc: @SodexisTeam

### CODE REVIEW

**Comment by pedrobaeza** [comment]
`[IMP] auth_admin_passkey: black, isort, prettier` commit contains a .deb file that shouldn't be there, and the version should be changed in the other commit. Another extra thing is that the commit message is not correct. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by amkarthik** [comment]
@pedrobaeza 
Done with the changes. 
Thanks

**Review by legalsylvain — APPROVED** [review]
Diff review. LGTM. thanks !

**Review by atchuthan — APPROVED** [review]
Code review :+1:

**Pull request merged**
