### PR TITLE
[12.0][FIX] fix ldaps certificate verification

### PR DESCRIPTION
**Pull request by huguesdk**
fix ldaps certificate verification when `skip_cert_validation` is `False`.

### CODE REVIEW

**Comment by huguesdk** [comment]
@alexey-pelykh could you please explain the reason why `connection.set_option(ldap.OPT_X_TLS_NEWCTX, 0)` is outside of the `if` block?

**Review by alexey-pelykh — APPROVED** [review]
@huguesdk I don't recall any specific reason, could be a bug.

**Review by remytms — APPROVED** [review]

**Comment by huguesdk** [comment]
glad that this was merged, thanks! what is the procedure to apply the same patch on higher versions?

**Comment by pedrobaeza** [comment]
You can cherry-pick the commit over upper branches and create the pull request the same as this one. I can fast-track it when done.

**Comment by huguesdk** [comment]
thanks @pedrobaeza. just created #358 and #359.

**Pull request merged**
