### PR TITLE
[12.0][MIG+REF] auth_admin_passkey

### PR DESCRIPTION
**Pull request by legalsylvain**
Port ``auth_admin_passkey`` from 10.0 to 12.0

**Main changes**
- repository (from server-tools to server-auth). Ref : https://github.com/OCA/server-tools/pull/1624#issuecomment-513891894
- configuration is now done via ``odoo.cfg`` config file, and not by ``ir.config.parameter`` settings. (more secure, more GDPR, and more simple code). [Ref](https://github.com/OCA/server-auth/issues/21). 
- various OCA convention

CC : @pedrobaeza, @alexis-via, @rvalyi, @eugen-don, @rafaelbn 

**One question to @Fenkiou**
 
You introduced the following code in that [commit](https://github.com/OCA/server-tools/commit/e16b37ae6d9c1cf71915d5a34a9b3651d0a23d12#diff-8ec5d043927ada610c80d69e6804860dR88) (PR [to port the module in V10](https://github.com/OCA/server-tools/pull/776)). I did'nt get this part. (I keep it, but I don't see it necessary).

            # Just be sure that parent methods aren't wrong
            user = self.sudo().search([('id', '=', self._uid)])
            if not user:
                raise

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
nice work @legalsylvain

**Comment by Olivier-LAURENT** [comment]
Tested... 👍 . Thx for the work @legalsylvain

**Comment by legalsylvain** [comment]
Thanks for the reviews, guys.

**Pull request merged**
