### PR TITLE
[MIG][11.0] auth_saml module migration

### PR DESCRIPTION
**Pull request by bodedra**
https://github.com/xcgd/auth_saml/issues/8
#11

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please respect commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by bodedra** [comment]
@pedrobaeza Thanks for your comment. Would you please provide me reference link to bring history from another repository?

**Comment by pedrobaeza** [comment]
The link provided before, in the section "Technical method...".

**Comment by bodedra** [comment]
@pedrobaeza I tried with following procedure to commit history but it fails.

screenshot from 2018-03-15 22 36 31

**Comment by max3903** [comment]
@bodedra Here is what I did to get the history from https://github.com/xcgd/auth_saml/tree/github_odoo9:
```
$ git clone https://github.com/OCA/server-auth.git -b 11.0
$ cd server-auth
$ git remote add xcdg git@github.com:xcgd/auth_saml.git
$ git fetch xcdg
$ git checkout xcdg/github_odoo9 -b 11.0-mig-auth_saml
$ git rebase -i origin/11.0
```
Then I moved all the files of the module in a subdirectory, copy the content of your branch and did some cleanup.

Please take it from here to fix the Travis errors. Let me know if you are stuck.

**Comment by bodedra** [comment]
Hello,

I have tried with same code as `auth_oauth` Odoo module has.

Reference code: https://github.com/odoo/odoo/blob/11.0/addons/auth_oauth/controllers/main.py#L132-L141

Implemented code: https://github.com/OCA/server-auth/pull/12/commits/96b88a39ddb312f9d9a39bedf1994c8c3a37639d#diff-b490068d8d8f46f24498caa7f0891817R173

Travis failed: https://travis-ci.org/OCA/server-auth/jobs/358985296#L623

Would you please suggest me ?

**Review by max3903 — APPROVED** [review]

**Review by jgrandguillaume — APPROVED** [review]
Thanks for the job. LGTM

**Review by smangukiya — APPROVED** [review]
Source look good to me. Good work there (y)

**Pull request merged**
