### PR TITLE
[14.0] Revert auth_api_key: fix api key archived user

### PR DESCRIPTION
**Pull request by TDu**

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
@TDu You can't revert the bump version... The wheel is already published on [pypi](https://pypi.org/project/odoo14-addon-auth-api-key/)

**Comment by TDu** [comment]
> @TDu You can't revert the bump version... The wheel is already published on [pypi](https://pypi.org/project/odoo14-addon-auth-api-key/)

Make sense, I kept the revert on the translation file, tho.

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
@lmignon is it OK for you?

**Review by lmignon — APPROVED** [review]

**Comment by simahawk** [comment]
/ocabot merge patch

@TDu could you propose another solution?
What about having a config param to enable this policy and explicitly check for user.active on lookup?

**Pull request merged**
