### PR TITLE
[18.0][MIG] auth_oidc: Migration to 18.0

### PR DESCRIPTION
**Pull request by ap-wtioit**
info @wt-io-it

### CODE REVIEW

**Comment by sbidoul** [comment]
I compared with 17, and it's identical.

Compared to 16, there are a couple of PR's that landed there that were never ported to 17 (#573, #650) - not saying you need to do it, just a note.

**Review by hparfr — APPROVED** [review]
LGTM (not tested yet)

**Comment by sbidoul** [comment]
Happy to merge this as soon as someone confirms it has been functionally tested.

**Review by wtaferner — APPROVED** [review]
Functionally tested within our own OAuth Provider Infrastructure and logged in successfully on the target test instance with OpenID

**Comment by hparfr** [comment]
Tested as well with keyloack; works as expected.

**Pull request merged**
