### PR TITLE
[MIG][15.0] auth_signup_verify_email

### PR DESCRIPTION
**Pull request by em230418**
Only changed version number

### CODE REVIEW

**Review by kanda999 — APPROVED** [review]
Functional review:It is working as expected under my v15 environment.

**Review by yostashiro — APPROVED** [review]
Functional review.

**Comment by nicomacr** [comment]
@em230418 could you check the conflicts in this PR?

**Comment by em230418** [comment]
Closing since https://github.com/OCA/server-auth/pull/430 is merged. Thanks @nicomacr!

**Pull request closed without merging**
