### PR TITLE
[14.0] [FIX] vault

### PR DESCRIPTION
**Pull request by AntoniRomera**
- Wrong field name

### CODE REVIEW

**Review by MRomeera — APPROVED** [review]

**Review by FernandoRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@fkantelberg Can you review this?.

**Review by fkantelberg — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@fkantelberg Sorry i added new one.

**Comment by AntoniRomera** [comment]
@OCA/core-maintainers Could you review?

**Review by hbrunn — APPROVED** [review]

**Review by fkantelberg — APPROVED** [review]

**Pull request merged**
