### PR TITLE
[14.0][MIG] auth_oauth_multi_token

### PR DESCRIPTION
**Pull request by dantiller2**

### CODE REVIEW

**Comment by dantiller2** [comment]
This is functional in it's present state. I'm able to login using it.

**Comment by sergio-teruel** [comment]
@dantiller2 Can you fix pre-commit? Thanks

**Comment by dantiller2** [comment]
> @dantiller2 Can you fix pre-commit? Thanks

Not sure how to go about that, but open to suggestions.

**Comment by sergio-teruel** [comment]
You can use command copier -f update the template
pre-commit fixed here https://github.com/OCA/server-auth/pull/441

**Comment by sergio-teruel** [comment]
Hy @dantiller2 Can you make a rebase?

**Comment by dantiller2** [comment]
Sergio, I rebased. This was new to me, but I think it's fine. ?
Also, I'm not sure if I should still run the copier update since you've branched off of this.

**Comment by sergio-teruel** [comment]
Hi... Any advance with this PR?

**Comment by pedrobaeza** [comment]
Sorry, the commit history is not correct and it's mixing a lot of files, so closing in favor of #471

**Pull request closed without merging**
