### PR TITLE
[15.0][MIG] auth_user_case_insensitive: Migration to 15.0 

### PR DESCRIPTION
**Pull request by Herqs**

### CODE REVIEW

**Comment by flachica** [comment]
I think that you should comment in #299 to point to this PR

**Comment by Herqs** [comment]
Hello @guimarc-br 

I've doublechecked, it seems that `user_agent_env` was added as a parameter to `res_user._login` method on v14. It was added to this module during v14 migration in this commit: https://github.com/OCA/server-auth/commit/c19ad6c520903336a1a1ee4f7574577dfd8f9e3e

Kind regards

**Review by kanda999 — APPROVED** [review]
Functional review : Working as expected

**Comment by CRogos** [comment]
What is missing on this PR?
Is the failed check really related to the changes by this PR?

**Comment by CRogos** [comment]
Code review: LGTM!

**Review by CRogos — APPROVED** [review]

**Comment by CRogos** [comment]
@pedrobaeza could you have a look? Could you trigger the merge?

**Comment by CRogos** [comment]
@pedrobaeza what needs to be done?

**Comment by pedrobaeza** [comment]
Please rebase and check the CI.

**Comment by CRogos** [comment]
@Herqs could you rebase your PR?

**Comment by dreispt** [comment]
Superseded by #428

**Pull request closed without merging**
