### PR TITLE
[13.0][BCK] vault, vault_share

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@fkantelberg

**Comment by rousseldenis** [comment]
Based on first version in v14

**Comment by fkantelberg** [comment]
@rousseldenis Cool. But wouldn't it be better to go from #302 because of the fixes? The PR only needs some final testing and reviews.

**Comment by rousseldenis** [comment]
> @rousseldenis Cool. But wouldn't it be better to go from #302 because of the fixes? The PR only needs some final testing and reviews.

You preceded my thoughts :smile: I want to merge this first, then backport your enhancements.

**Comment by fkantelberg** [comment]
@rousseldenis The PR #302 was merged. Can you update this PR? I would try to run the tests afterwards.

**Comment by rousseldenis** [comment]
@fkantelberg I've rebased this.

I tried your PR cherry-pick but too much conflicts.

Maybe we could merge this, then do a PR for backport #302 ?

**Comment by fkantelberg** [comment]
@rousseldenis I discovered a bug in the meantime with the key password #374 

Wouldn't it be easier to take the newer 14.0 branch and reapply the patches for v13? Most of it is just reapplying pre-commit and some commenting of templates/views/acls to make it work for v13.

**Comment by rousseldenis** [comment]
@fkantelberg Please review this instead : https://github.com/OCA/server-auth/pull/384

**Pull request closed without merging**
