### PR TITLE
[13.0][MIG] auth ldap user pattern

### PR DESCRIPTION
**Pull request by Khalid-SerpentCS**
Auth LDAP User Pattern
===================

This module will support additional features for LDAP

### CODE REVIEW

**Review by dreispt — CHANGES_REQUESTED** [review]
The commit history is missing.
You need to import the history from the 12.0 version using this recipe: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

**Comment by dreispt** [comment]
Also, if you run autoformatting, make sure that is done in a separate commit, so that we can have a commit with only  the technical changes to review. Thank you!

**Comment by bodedra** [comment]
Ping @Khalid-SerpentCS

**Comment by bodedra** [comment]
Ping @Chandresh-SerpentCS

**Comment by dreispt** [comment]
Replaced by #176

**Pull request closed without merging**
