### PR TITLE
Fix: replace tenant id for single tentant

### PR DESCRIPTION
**Pull request by janikvonrotz**
Moved `-  replace {tenant_id} in urls with your Azure tenant id` to the correct section in the readme.

### CODE REVIEW

**Comment by gurneyalex** [comment]
@janikvonrotz you should not change the README.rst file directly: this file is generated by the files in the readme/ subdirectory -> this is where you change must be.

**Comment by janikvonrotz** [comment]
@gurneyalex Ah, I'm supposed to know this. Sry.

**Comment by gurneyalex** [comment]
hello @janikvonrotz , why did you close the PR and not update it?

**Comment by janikvonrotz** [comment]
@gurneyalex I used the GitHub UI to edit the file and create the PR, as far as I know I cannot update it from the GitHub UI.

**Pull request closed without merging**
