### PR TITLE
[17.0][MIG] auth_signup_verify_email

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by zuher83 — APPROVED** [review]
Functional review

**Comment by carolinafernandez-tecnativa** [comment]
Could you please rebase and squash administrative commits? Thanks

TT50109

**Comment by carolinafernandez-tecnativa** [comment]
@augusto-weiss Could you please rebase and squash administrative commits?
Please check precommit failure.Thanks

**Comment by pedrobaeza** [comment]
Let's try to merge it as is, although not sure if the pre-commit fail will arise:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Continued in #681

**Pull request closed without merging**
