### PR TITLE
[I18N] password_security: Translate to Spanish all translatable terms

### PR DESCRIPTION
**Pull request by luisg123v**
This translates to Spanish all missing translations, 31 in total.

[ci skip]

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use new translation system: https://odoo-community.org/blog/our-blog-1/post/translations-platform-81 and avoid some typos that I have already detected in this PR (lower instead upper case, `contraceñas` instead on `contraseñas`...).

**Comment by luisg123v** [comment]
@pedrobaeza 
This project seems to not be in Weblate yet.

**Comment by pedrobaeza** [comment]
Yeah, a first commit is needed for being activated. Let's make this time through the PR, but please fix the terms as said.

**Comment by luisg123v** [comment]
@pedrobaeza 
Done, I fixed the cases you mentioned, trying to be as careful as possible.

I also removed `[ci skip]` from the commit message, because I imagine that is required for Weblate for making its work

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
