### PR TITLE
[15.0][MIG] users_ldap_groups

### PR DESCRIPTION
**Pull request by ortlam**

### CODE REVIEW

**Comment by OSevangelist** [comment]
@dsolanki-initos would you mind to review this. @ortlam has already ported the module as discussed. Thanks a lot!

**Review by dsolanki-initos — APPROVED** [review]
Done code review, Looks good to me

**Comment by OSevangelist** [comment]
@dreispt or @sbidoul we've migrated this upon customer request (@ortlam) and reviewed it (@dsolanki-initos). Would anyone you officially PSC of this repo invoke the merge bot as i am capable but usually not allowed to do so ;-) Thx and happy x-mas

**Pull request merged**
