### PR TITLE
[13.0][MIG] auth_ldaps

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
enhancement over #179

**Comment by gurneyalex** [comment]
@alexey-pelykh you reviewed #179 -> this one fixes the runbot error we had on that PR. Can you review it?

**Review by alexey-pelykh — APPROVED** [review]

**Review by bodedra — APPROVED** [review]
@gurneyalex appreciate your efforts to resolve package error and make it :green_apple:

**Pull request merged**
