### PR TITLE
[13.0][MIG] password_security

### PR DESCRIPTION
**Pull request by llacroix**
Migration to 13.0 of password_security based on PR from https://github.com/OCA/server-auth/pull/189

With history exported

### CODE REVIEW

**Comment by llacroix** [comment]
https://github.com/OCA/server-auth/pull/239/commits/f230f4357faa8e7019d5fd7cece5409fd7eaabe5
https://github.com/OCA/server-auth/pull/239/commits/e3ce1401998cc337e729ab64f01cbf90c6f89a45

Those two commits are from the PR and the newest ones are forward ported from 12.0

**Comment by mcassuto** [comment]
@gurneyalex can we have a review here and close these 2 PR ?

Thanks

**Comment by llacroix** [comment]
I squashed the format commits. If there is an issue I'll add separate commits from the reformatting. So we know which changes are introduced.

**Comment by mcassuto** [comment]
Can we have someone to approve this PR ?

**Comment by llacroix** [comment]
@pedrobaeza could you have a look?

**Comment by pedrobaeza** [comment]
Sorry, I don't use this module.

**Comment by llacroix** [comment]
Any idea who could review this?

**Review by gurneyalex — APPROVED** [review]

**Comment by llacroix** [comment]
@gurneyalex anything else to get it merged?

**Review by dreispt — APPROVED** [review]

**Pull request merged**
