### PR TITLE
[13.0] [MIG] auth_ldap_user_pattern: Migrated module in v13.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**
Depends on 
* [ ] #147

### CODE REVIEW

**Comment by bodedra** [comment]
@Chandresh-SerpentCS Please do not remove copyrights.

**Comment by Chandresh-SerpentCS** [comment]
Need to close #160

**Review by dreispt — CHANGES_REQUESTED** [review]
The commit history is missing

**Comment by dreispt** [comment]
I'm sorry, checking on #147 I realize that we do have the full history.

**Pull request closed without merging**
