### PR TITLE
[12.0][IMP][WIP]Add zxcvbn to password security

### PR DESCRIPTION
**Pull request by fkantelberg**
This PR should implement an additional password security measure with zxcvbn.

It currently uses the zxcvbn js lib for the client side meter to limit the number of requests. This could result in divergence between both.

### CODE REVIEW

**Comment by moylop260** [comment]
Thanks!
Could you add an entry for `requirements.txt` file, please?

**Comment by fkantelberg** [comment]
@moylop260 
Yes sure

**Comment by moylop260** [comment]
Thanks @fkantelberg 

FYI I have reproduced the following error:

```bash
Uncaught ReferenceError: zxcvbn is not defined
http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:4040
Traceback:
ReferenceError: zxcvbn is not defined
    at Class._estimate (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:4040:81)
    at Class.score (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:4040:582)
    at Object.computeScore (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:4030:231)
    at Class.update (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:4030:1357)
    at http://3385571-130-275809.runbot1.odoo-community.org/web/content/377-3e84e24/web.assets_backend.js:2485:1058
    at http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:802:681
    at fire (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:796:299)
    at Object.add [as done] (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:797:467)
    at Array.<anonymous> (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:802:649)
    at Function.each (http://3385571-130-275809.runbot1.odoo-community.org/web/content/371-7285eeb/web.assets_common.js:625:767)
```

Check the following git:
 - error gif

**Comment by fkantelberg** [comment]
@moylop260 You are right. The gitignore prevented the js lib from being uploaded. Should be fixed now

**Comment by eilst** [comment]
I tested locally, i works now :+1: 
passwordsec2
passwordsec

**Pull request merged**
