### PR TITLE
[13.0][MIG] vault and vault_share: Migration to 13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT37022

superseded from https://github.com/OCA/server-auth/pull/384

ping @fkantelberg @pedrobaeza

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza @CarlosRoca13 Could you check why tests are failing ?

**Comment by rousseldenis** [comment]
@CarlosRoca13 Could you rebase ?

**Comment by CarlosRoca13** [comment]
Done! :smile:

**Review by rousseldenis — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
