### PR TITLE
[15.0][MIG]user_log_view: Migration to 15.0

### PR DESCRIPTION
**Pull request by Tisho99**

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
Functional review. @pedrobaeza I'm sure this module might be useful for you 😉.

Could make a quick review and merge in case it's correct?

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration user_log_view
/ocabot merge nobump

**Pull request merged**
