### PR TITLE
[17.0][FIX] impersonate_login: fix computed body field

### PR DESCRIPTION
**Pull request by astirpe**
Fix bug in compute method + computed body should be writable

### CODE REVIEW

**Comment by astirpe** [comment]
@CasVissers-360ERP @StefanRijnhart

**Comment by CasVissers-360ERP** [comment]
@dreispt @Kev-Roche I think this fix should be fast tracked. We missed this in our tests, the fixed bug has a big impact.

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by Kev-Roche — APPROVED** [review]

**Pull request merged**
