### PR TITLE
[12.0][MIG] auth_from_http_remote_user from 11 to 12

### PR DESCRIPTION
**Pull request by warp10**

### CODE REVIEW

**Comment by OpenCode** [comment]
@OCA/server-environment-maintainers Any reviews?

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@OpenCode where's yours? :smile_cat:

**Comment by pedrobaeza** [comment]
@gurneyalex ocabot stuck. Please relaunch

**Pull request merged**
