### PR TITLE
[14.0][MIG] auth_signup_verify_email

### PR DESCRIPTION
**Pull request by em230418**
In summary:
- added 1 lint commit
- added 1 migration commit
- squashed https://github.com/OCA/server-auth/commit/8edad9a0e2d7568b73cfa91dde8e55bd0252fca7 and 8edad9a0e2d7568b73cfa91dde8e55bd0252fca7 into https://github.com/OCA/server-auth/commit/ce19da941e3c8f3c8863662745845c874588128d

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is red

**Comment by em230418** [comment]
Travis is green now, should I cover lines reported by codecov?

**Review by ernestotejeda — APPROVED** [review]
Code and functional review 👍🏼

**Comment by ernestotejeda** [comment]
ping @Tardo @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
