### PR TITLE
[MIG] auth_signup_verify_email: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Review by victoralmau — CHANGES_REQUESTED** [review]
Can you fix pre-commit errors and tests?

Please, add https://github.com/OCA/server-auth/pull/388 to history commit

**Comment by victoralmau** [comment]
Could you rebase to solve the pre-commit problem?

**Comment by nicomacr** [comment]
> Could you rebase to solve the pre-commit problem?

Done!!

**Review by victoralmau — APPROVED** [review]
Thanks.
Code review OK

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
