### PR TITLE
[16.0][MIG] auth_oidc: Migration to 16.0

### PR DESCRIPTION
**Pull request by jaenbox**
Standard migration to 16.0

### CODE REVIEW

**Review by Abranes — APPROVED** [review]
Tested on keycloak on local.

**Review by adrienpeiffer — APPROVED** [review]
Code review + tests

**Comment by adrienpeiffer** [comment]
@OCA/server-environment-maintainers could you merge this one ?

**Comment by adrienpeiffer** [comment]
@OCA/server-environment-maintainers No one ? :pray:

**Comment by ashuio** [comment]
Any ETA on this merge? We are running EE and would really appreciate this fix.

@OCA/server-environment-maintainers

**Comment by theangryangel** [comment]
@jaenbox any chance this could be rebased? <3

**Comment by jaenbox** [comment]
> @jaenbox any chance this could be rebased? <3

done!!

**Review by theangryangel — APPROVED** [review]
Functionally tested.

**Comment by CRogos** [comment]
@gurneyalex could you have a look why this is not merged yet?

**Pull request merged**
