### PR TITLE
[IMP] auth_api_key: decouple server_environment, making it optional

### PR DESCRIPTION
**Pull request by dreispt**
Server Environment is a dependency, but it is not really required.
Server Environment requires specific configuration, and the Odoo service fails to start without it.
IMO there is not good reason to force it to be used.

### CODE REVIEW

**Comment by dreispt** [comment]
The build fails while installing, I'm not convinced it is related to my change.

Trying to build locally, I get a different error, coming from `server_environment`:

image

Additional help is appreciated. Thanks!

**Comment by dreispt** [comment]
It was a module bug. Fixed, ready for review!

**Comment by dreispt** [comment]
Needs review please!

**Review by lmignon — APPROVED** [review]
Thank you @dreisptè Useful change. LGTM (Code review)

**Review by ypapouin — APPROVED** [review]
LGTM - Code Review

**Pull request merged**
