### PR TITLE
[13.0] [MIG] users_ldap_mail: Migration to 13.0

### PR DESCRIPTION
**Pull request by joao-p-marques**
@Tecnativa 
TT27069

Tested with local LDAP server.

ping @pedrobaeza @Tardo @dreispt

### CODE REVIEW

**Review by Tardo — APPROVED** [review]
LGTM :+1: code review.

**Comment by pedrobaeza** [comment]
Please squash a bit commits from the beginning where the author is the same.

**Comment by joao-p-marques** [comment]
@pedrobaeza I squashed some of the commits and also added a little note for future tests if we want.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
