### PR TITLE
[11.0][ADD] Auth SAML Groups

### PR DESCRIPTION
**Pull request by eilst**

### CODE REVIEW

**Review by lgharib — APPROVED** [review]

**Comment by eilst** [comment]
Hey @max3903 @pedrobaeza @vincent-hatakeyama, I added this feature of giving the option to automatically add users to odoo groups from the saml groups with a given matching attribute when users logs in with an idp. I base this pr on @vincent-hatakeyama, which fixes some important issues that exist on 11.0.

**Comment by max3903** [comment]
@eilst Try to rebase your branch on 12.0. That may help.

**Review by wbeverly — APPROVED** [review]

**Review by rimbendhaou — APPROVED** [review]

**Comment by moylop260** [comment]
For record,
It depends from:
 - https://github.com/OCA/server-auth/pull/107

Rebase it after merging it

**Comment by moylop260** [comment]
Hi @eilst 

Could you check the following error, please?
 - [2019-08-28 19:39:36,376 5467 ERROR openerp_test odoo.addons.auth_saml_groups.tests.test_auth_saml_groups: ` AttributeError: module 'lasso' has no attribute 'Server'](https://travis-ci.org/OCA/server-auth/jobs/578025293#L988)


I just reproduced it using the following script:
```python
pip install lasso

python -c "import lasso;lasso.Server"
```

Output: `AttributeError: module 'lasso' has no attribute 'Server'`

**Comment by eilst** [comment]
Hey @moylop260,
Thank you for your review
I was thinking to remove the test and put in in version 'beta'. Because,
this module requires the python3-lasso package. The pip lasso package is not the right one.

So an `apt-get install python3-lasso` is needed.
Is it possible to install system packages in travis?

**Comment by moylop260** [comment]
Hi @eilst 

Yes it is possible installing system package in travis, you will need to apply the following patch:

```diff
diff --git a/.travis.yml b/.travis.yml
index fc8aacf..7f64815 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -13,6 +13,7 @@ addons:
       - expect-dev  # provides unbuffer utility
       - python-lxml # because pip installation is slow
       - libmysqlclient-dev # To install mysqlclient and import MySQLdb
+      - python3-lasso

 env:
   global:
```

So, you can remove the bad requirements.txt dependency.
Regards!

**Pull request merged**
