### PR TITLE
[14.0][UPD] auth_api_key(_server_env) development status

### PR DESCRIPTION
**Pull request by qgroulard**
@simahawk @lmignon 

Could we consider moving those modules to "Production/Stable" ?
They will be used once more at Acsone.

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]

**Comment by sbidoul** [comment]
@simahawk any particular reason why auth_api_key_server_env was Alpha ?

**Comment by simahawk** [comment]
I split out the dependency of server_environment only recently... that was the reason :wink:

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@qgroulard next time pls:
1. use 1 commit per module w/ its own name
2. do not put the odoo version in the commit msg :heavy_check_mark:  (just a reminder :wink: )

thanks! :pray:

**Pull request merged**
