### PR TITLE
[17.0][MIG] auth_api_key_server_env: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Ref: BSRD-708

### CODE REVIEW

**Comment by gurneyalex** [comment]
depends on 

- [x] https://github.com/OCA/server-auth/pull/591
- [x] https://github.com/OCA/server-env/pull/168

**Comment by gurneyalex** [comment]
@nguyenminhchien dependencies are now merged. Can you rebase and remove the unreleased dependencies?

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien dependencies are now merged. Can you rebase and remove the unreleased dependencies?

done.

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
