### PR TITLE
[15.0][MIG] vault and vault_share

### PR DESCRIPTION
**Pull request by fkantelberg**
This is the migration of both vault modules to version 15.0 with migrating most of the JS to the newer esm.

### CODE REVIEW

**Comment by CRogos** [comment]
To fix build, please rebase.

**Comment by CRogos** [comment]
Did you follow the migration tasks?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

I think some commits need to be squashed, the version needs to be corrected, ... I know, I went throw this hell myself, but in the end we all profit from it.

**Comment by fkantelberg** [comment]
@CRogos Thank you for the reminder. I did it at the start but afterwards some fixes came up for the other branches and the history got messy because of it. There are currently 2 active PR for problems in 13.0 and 14.0 afterwards I can clean up the history here again.

**Comment by fkantelberg** [comment]
@CRogos I rebased everything and the commit history should be fine. Functional tests are also all green.

**Comment by CRogos** [comment]
Looks better now. I think It is not an big issue but for the future, there should be two commits:
[IMP] $MODULE: black, isort, prettier
[MIG] $MODULE: Migration to 15.0

The pre-commit issue should be fixed by PR: https://github.com/OCA/server-auth/pull/453
maybe you can rebase as soon as it is available in the 15.0 branch.

**Comment by pedrobaeza** [comment]
Pre-commit fix merged.

**Review by CarlosRoca13 — APPROVED** [review]
All working well :+1: 

But please add this change when PR is merged :smile: https://github.com/OCA/server-auth/pull/499

**Comment by pedrobaeza** [comment]
@fkantelberg can you add the missing PR for merging this?

**Pull request merged**
