### PR TITLE
[13.0][MIG] auth_oauth_multi_token

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by fmdl** [comment]
@simahawk

**Comment by simahawk** [comment]
@fmdl you should make pre-commit happy :wink:

**Comment by janikvonrotz** [comment]
```
$ pre-commit run --all --show-diff-on-failure --verbose --color always

black....................................................................Failed
```

Can I help to fix this? Why is pre-commit unhappy? I'm gonna have a look.

**Comment by yajo** [comment]
You should follow the guide at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 and split pre-commit changes from real migration changes.

@Tecnativa TT25619

**Comment by yajo** [comment]
This is stale, see #218.

**Pull request closed without merging**
