### PR TITLE
[12.0] [IMP] password_security remaining translatable messages

### PR DESCRIPTION
**Pull request by valentincastravete**

### CODE REVIEW

**Comment by TheRaphael0000** [comment]
Hello,

Here @CompassionCH, we are interested in this pull request.
When do you think this will be merged into the 12.0 branch ?

Kind regards.

**Review by ecino — APPROVED** [review]

**Review by eicher31 — APPROVED** [review]

**Comment by TheRaphael0000** [comment]
Hi,

I think we should use the implementation from 14.0 instead.
It's better for translation since the sentences are not broken into multiple parts.
https://github.com/OCA/server-auth/blame/14.0/password_security/models/res_users.py#L84

**Comment by TheRaphael0000** [comment]
I've made a PR here : https://github.com/OCA/server-auth/pull/327

**Review by JorgeQuinteros — APPROVED** [review]
LGTM! Functional Review

**Comment by valentincastravete** [comment]
There's a better PR here : #327

**Pull request closed without merging**
