### PR TITLE
[CI] auth_totp_password_security: test independently

### PR DESCRIPTION
**Pull request by yajo**
Tests in module `auth_totp_password_security` are weird. They seem to be testing implementation rather than behavior. And they are trying to workaround HTTP instead of using an `HttpCase`. As a result, if tests from `password_security` are run along with those of `auth_totp_password_security`, the latter ones fail.

This is not a real fix, but it is the easiest way to respect test resilience in `password_security` and make all go green.

Someone with more interest in `auth_totp_password_security` should fix those nasty tests.

This reverts commit 492201a from https://github.com/OCA/server-auth/pull/159

@Tecnativa TT22338

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems the exclude doesn't work due to the auto_install. Then you need to exclude both `auth_totp` and `auth_totp_password_security`.

**Comment by yajo** [comment]
Before that, the worse part is that the INCLUDE doesn't work either. It tests password_security and thus breaks tests for auth_totp_password_security.

Is there anything else I can do apart from rewriting the tests? :roll_eyes: I'm out of ideas.

**Comment by pedrobaeza** [comment]
I don't have either...

**Comment by yajo** [comment]
How about removing the bad tests? I know that will decrease coverage, but tests are bad designed anyway...

**Comment by pedrobaeza** [comment]
OK, if it's the only way, and obviously as it's not really testing the feature, only the implementation.

**Comment by yajo** [comment]
OK, wrong tests removed.

**Review by pedrobaeza — APPROVED** [review]
Let's fast-track this for solving the CI status

**Pull request merged**
