### PR TITLE
[MIG] password_security to 11

### PR DESCRIPTION
**Pull request by mart-e**
Move to server-auth
Bump version number
Remove coding utf-8

_As it is the [hacktoberfest](https://hacktoberfest.digitalocean.com/), it is the occasion to help outside projects than Odoo_

Note: while testing this module, I noticed the error message during signup to be badly formed (`('Password must be 12 characters or more.\rMust contain the following:\r\n* Lowercase letter\r\n* Uppercase letter\r\n* Numeric digit\r\n* Special character', '')`) but it looks this is actually a bug of `auth_signup` that `UserError` are not properly displayed in the signup form.
Will check on core how to fix that so you may want to wait that this bug is fixed before merging this one.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mart-e how good is to see you contributing to OCA! Thanks for the PR.

I see that you have realized about the split of server-tools as it was very over-crowded. The only problem is about commit history. Please see migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0, but in this case you will need to add as remote server-tools and change slightly the `git am` command for catching the commits from this repo instead of origin, but nothing complicated for a git-fu like you :wink:

**Review by lasley — APPROVED** [review]
Thanks @mart-e

**Comment by pedrobaeza** [comment]
There's already another PR for the same module in #3. This one passes all the CIs and the other not, but we should agree what to do, as first PR usually has priority.

**Comment by mart-e** [comment]
Oh I missed that one. Sure, if he fixes all the issues, it should have the priority obviously.

**Comment by mart-e** [comment]
FYI, the issue in the rendering of the error message was fixed upstream at odoo/odoo@c3bf1618bd9

**Comment by pedrobaeza** [comment]
Thanks for that, Martin!

**Review by yajo — APPROVED** [review]
code review

**Comment by yajo** [comment]
Oops, I think we should close this in favor of #3, no?

**Pull request closed without merging**
