### PR TITLE
14.0 mig auth dynamic groups

### PR DESCRIPTION
**Pull request by KKamaa**
Migration of **auth_dynamic_groups** to version 14.0

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@KKamaa Could you squash the last 3 commits? In the first, you are changing " to ', and in the next, you are changing it back, so it's a bit cumbersome to read.

**Comment by KKamaa** [comment]
@thomaspaulb commits squashed.

**Comment by thomaspaulb** [comment]
@KKamaa Great looking clean now, let's see what testing brings.

**Review by gjotten — APPROVED** [review]
Finally got around to testing this functionally for a bit. Very simply through `user.name == 'Marc Demo'` on `dynamic_group_condition`, running `action_evaluate` afterwards, and subsequently clearing `users` and logging in with user 'demo'. 

All went well so LGTM, @thomaspaulb I think a code review is in order here as well.

**Review by thomaspaulb — APPROVED** [review]
Code review.

**Pull request merged**
