### PR TITLE
[FIX][14.0] auth_saml: readme an link to the runboat

### PR DESCRIPTION
**Pull request by leemannd**
These changes where introduced with the backport of the refactoring of the module auth_saml
in -> https://github.com/OCA/server-auth/commit/cd6082aef3150d089317795a53a057d4452aeaf7

In this PR I change them back to values related to 14.0 for more consistency

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @vincent-hatakeyama Can you have a look at this README and runboat link update?

**Review by apf-c2c — APPROVED** [review]
LGTM

**Comment by vincent-hatakeyama** [comment]
Those files are automatically updated by the runbot.

For the information about the changes, you need to edit readme/HISTORY.rst that is used by the runbot.

**Comment by vincent-hatakeyama** [comment]
@OCA/tools-maintainers The author of this PR tries to fix the index.html file directly but that file is supposed to be generated automatically. The README of the 14.0 branch is correct but [auth_saml/](https://github.com/OCA/server-auth/blob/14.0/auth_saml/static/description/index.html#L84) references the 15.0 branch. Is there a way to force the bot to do the update?

**Comment by dreispt** [comment]
@vincent-hatakeyama Something went wrong there. Recent version of pre-commit ensure the README is generated.

**Comment by thomaspaulb** [comment]
@dreispt @pedrobaeza Should we maybe do a manual merge in this situation? It's just readme updates so there's no harm done

**Comment by hbrunn** [comment]
seems to me you fell victim of https://github.com/OCA/oca-addons-repo-template/issues/250#issuecomment-2084674256 - retry?

/ocabot merge patch

**Comment by pedrobaeza** [comment]
You have to wait until the situation with Codecov is resolved.

**Comment by leemannd** [comment]
Closing as old and outdated

**Pull request closed without merging**
