### PR TITLE
[15.0][IMP] password_security: Speed up tests.

### PR DESCRIPTION
**Pull request by amh-mw**
Switched from TransactionCase to SavepointCase.
Removed sleeps.
Test runtime reduced by about six seconds.

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
The sleep was introduce to avoid problems sometimes when the mark is the same on the several checks. Please do git blame to see why it was introduced.

**Comment by amh-mw** [comment]
> The sleep was introduce to avoid problems sometimes when the mark is the same on the several checks. Please do git blame to see why it was introduced.

I surmised that the tests often created the user, then wrote `password_write_date` within the same second boundary, so I manually set `password_write_date` to the Unix epoch. Is there something else I'm missing?

**Review by pedrobaeza — APPROVED** [review]
OK then :)

/ocabot merge patch

**Pull request merged**
