### PR TITLE
[14.0] [MIG] auth_api_key module

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@chafique-delli hello could you rebase your PR and recheck the precommit step, the merge by ocabot failed there, because of the website key in the manifest https://travis-ci.com/github/OCA/server-auth/jobs/453802850#L415

**Pull request merged**
