### PR TITLE
[12.0][ADD] auth_ldap_attributes_sync

### PR DESCRIPTION
**Pull request by alexey-pelykh**
An enhanced replacement for `users_ldap_mail`

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please remove the plural from the module name as you are now changing it and check CIs status?

**Comment by alexey-pelykh** [comment]
you mean `attribute` instead of `attributes`?

**Comment by pedrobaeza** [comment]
Yes, you can check at https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules that it's encouraged to do that for avoiding problems on the spelling, although historical modules that have been migrated version per version still continue with some plurals (or Odoo itself doesn't follow this rule).

**Comment by alexey-pelykh** [comment]
Moved to #45

**Comment by pedrobaeza** [comment]
As a note, you don't need to open a new PR. Just force pushing this one you can replace entire content.

**Comment by alexey-pelykh** [comment]
Thanks for a hint! I've failed to find a way to change branch (which was renamed) of the PR, thus had to create a new one

**Comment by pedrobaeza** [comment]
Oh, yeah, in that case, you can't do it, but hey, I don't rename branches in that cases. Only change the name of the module, commit with amend and forced push.

**Pull request closed without merging**
